services:
  web:
    build: ./html
    ports:
      - 8080:80
    develop:
      watch:
        - action: sync
          path: ./html/
          target: /usr/local/apache2/htdocs/

  flask-app:
    build: .
    ports:
      - 5000:5000
    develop:
      watch:
        - action: sync+restart
          path: ./flask-app/
          target: /app